version: '3'
services:
  httpd:
    container_name: mds_httpd
    build: './httpd'
    ports:
      - "80:80"
    volumes:
      - ./html:/var/www/html
  mysql:
    container_name: mds_mysql
    platform: linux/x86_64
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mds
      MYSQL_USER: mds
      MYSQL_PASSWORD: mds
  php:
    container_name: mds_php
    image: php:7.4-fpm-alpine
    volumes:
      - ./html:/var/www/html
    depends_on:
      - httpd
    expose:
      - "80"
  phpmyadmin:
    container_name: mds_phpmyadmin
    image: phpmyadmin:5.1.3
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mds_mysql
      PMA_USER: mds
      PMA_PASSWORD: mds
    depends_on:
      - mysql